-- 2 Parte PROCEDURES

USE CLASSICMODELS;


-- QUESTÃO 11
DELIMITER $
CREATE PROCEDURE TODOS_CUSTOMERS ()
BEGIN
   Select * from CUSTOMERS;
END$
DELIMITER ;
CALL TODOS_CUSTOMERS;


-- QUESTÃO 12
DELIMITER $
CREATE PROCEDURE PRODUTOS_VENDIDOS (IN PARAM_ESCRITORIO VARCHAR(50), IN PARAM_ANO VARCHAR(4))
BEGIN
   
   SELECT PRODUCTS.PRODUCTNAME PRODUTO, SUM(QUANTITYORDERED) QUANTIDADE, OFFICES.CITY ESCRITORIO, REQUIREDDATE DATAP
   FROM
   PRODUCTS JOIN
   ORDERDETAILS USING(PRODUCTCODE)
   JOIN ORDERS USING(ORDERNUMBER)
   JOIN CUSTOMERS USING(CUSTOMERNUMBER)
   JOIN EMPLOYEES ON(EMPLOYEES.EMPLOYEENUMBER = CUSTOMERS.SALESREPEMPLOYEENUMBER)
   JOIN OFFICES USING(OFFICECODE)
   WHERE OFFICES.CITY = PARAM_ESCRITORIO AND YEAR(ORDERDATE) = PARAM_ANO 
   GROUP BY PRODUTO;
END$
DELIMITER ;
CALL PRODUTOS_VENDIDOS('NYC', '2003');


-- QUESTÃO 13
DELIMITER $
CREATE PROCEDURE CLIENTES_ESCRITORIO ()
BEGIN
   
   SELECT OFFICES.CITY ESCRITORIO, CUSTOMERS.CUSTOMERNAME CLIENTE
   FROM
   CUSTOMERS
   JOIN EMPLOYEES ON(EMPLOYEES.EMPLOYEENUMBER = CUSTOMERS.SALESREPEMPLOYEENUMBER)
   JOIN OFFICES USING(OFFICECODE)
   ;
END$
DELIMITER ;
CALL CLIENTES_ESCRITORIO();


-- QUESTÃO 14
DELIMITER $
CREATE PROCEDURE PRODUTOS_ANO (OUT PARAM_PRODUTOSVENDIDOS INT, IN PARAM_ANO VARCHAR(4))
BEGIN
   
   SELECT SUM(QUANTITYORDERED) QNT_PRODUTOS INTO PARAM_PRODUTOSVENDIDOS
   FROM
   ORDERDETAILS
   JOIN ORDERS USING(ORDERNUMBER)
   WHERE YEAR(ORDERDATE) = PARAM_ANO
   GROUP BY YEAR(ORDERDATE);

END$
DELIMITER ;
CALL PRODUTOS_ANO(@QNT,'2003');
SELECT @QNT;


-- QUESTÃO 15
DELIMITER $
CREATE PROCEDURE DEZ_PRODUTOS (IN PARAM_ANO VARCHAR(4), OUT RESPOSTA VARCHAR(100))
BEGIN
   DECLARE VAR_TOTAL_VENDAS INT;
   DECLARE VAR_QNT_VENDIDA INT;
   
/* SELECT SUM(QUANTITYORDERED) QNT_VENDIDA, (quantityOrdered * priceEach) TOTAL_VENDIDO, PRODUCTCODE PRODUTO
   FROM
   ORDERDETAILS JOIN ORDERS USING(ORDERNUMBER)
   WHERE YEAR(ORDERDATE) = '2003'
   GROUP BY PRODUTO
   ORDER BY QNT_VENDIDA LIMIT 10; */
   
   SELECT SUM(QUANTITYORDERED) QNT_VENDIDA INTO VAR_QNT_VENDIDA
   FROM
   ORDERDETAILS JOIN ORDERS USING(ORDERNUMBER)
   WHERE YEAR(ORDERDATE) = PARAM_ANO 
   GROUP BY PRODUCTCODE
   ORDER BY QNT_VENDIDA LIMIT 1;
   
   SELECT (quantityOrdered * priceEach) TOTAL_VENDIDO INTO VAR_TOTAL_VENDAS
   FROM
   ORDERDETAILS JOIN ORDERS USING(ORDERNUMBER)
   WHERE YEAR(ORDERDATE) = PARAM_ANO 
   GROUP BY PRODUCTCODE
   ORDER BY TOTAL_VENDIDO LIMIT 1;
   
   IF VAR_TOTAL_VENDAS = VAR_TOTAL_VENDAS THEN
		SET RESPOSTA =  "Produto Acima das Expectativa";
	ELSE
		SET RESPOSTA =  "Produtos diferentes";
	END IF;
END$
DELIMITER ;
CALL DEZ_PRODUTOS('2003', @RESP);
SELECT @RESP;

-- QUESTÃO 20
CREATE TABLE Taxa_Crescimento_De_Venda (
    Id_Vendedor INT,
    Nome_Vendedor VARCHAR(100),
    Ano INT,
    Valor_Janeiro_base FLOAT,
    Taxa_Fevereiro VARCHAR(5),
    Taxa_Marco VARCHAR(5),
    Taxa_Abril VARCHAR(5),
    Taxa_Maio VARCHAR(5),
    Taxa_Junho VARCHAR(5),
    PRIMARY KEY (Id_Vendedor, Ano)  
);

   
  