use sakila;

CREATE OR REPLACE VIEW CLIENTE_LOCADORA (PAIS, CIDADE, CODIGO, NOME, EMAIL, VALOR)
AS
SELECT 
  COUNTRY, 
  CITY,
  CUSTOMER_ID,
  CONCAT(FIRST_NAME, ' ', LAST_NAME) NOME, 
  EMAIL, 
  SUM(AMOUNT)
  
FROM 
  COUNTRY
    JOIN CITY USING (COUNTRY_ID)
    JOIN ADDRESS USING (CITY_ID)
    JOIN CUSTOMER USING (ADDRESS_ID)
    JOIN PAYMENT USING (CUSTOMER_ID)
GROUP BY 
  COUNTRY, CITY, CUSTOMER_ID, NOME, EMAIL;
    
    

SELECT * FROM CLIENTE_LOCADORA;

CREATE OR REPLACE VIEW DADOS_LOCADORA_PAIS (TOTALRECEBIDO, QTDECLIENTE, PAIS)
AS
SELECT 
   SUM(AMOUNT), 
   COUNT(CODIGO),
   PAIS
FROM 
   CLIENTE_LOCADORA
     JOIN PAYMENT ON (CODIGO = CUSTOMER_ID)
GROUP BY 
  PAIS;
  
SELECT * FROM DADOS_LOCADORA_PAIS;

CREATE OR REPLACE VIEW CLIENTES
AS
SELECT * FROM CUSTOMER;


SELECT * FROM CLIENTES;

DELETE FROM CLIENTES WHERE CUSTOMER_ID = 10;

DELETE FROM CLIENTE_LOCADORA WHERE CODIGO = 218;



WITH 
  DADOS_CATEGORIA AS (
   SELECT
     NAME AS CATEGORIA,
     CATEGORY_ID,
     COUNT(FILM_ID) QTDE_FILME
   FROM 
     CATEGORY 
       JOIN FILM_CATEGORY USING (CATEGORY_ID)
   GROUP BY 
     CATEGORIA
  ),
  DADOS_FILME AS(
    SELECT 
      TITLE, 
      CATEGORY_ID,
      LENGTH
	  REPLACEMENT_COST
	FROM 
      FILM
        JOIN FILM_CATEGORY USING (FILM_ID)
        JOIN CATEGORY USING (CATEGORY_ID)
  )

SELECT * FROM DADOS_CATEGORIA JOIN DADOS_FILME USING (CATEGORY_ID);


SELECT * FROM DADOS_CATEGORIA;


WITH DADOS_CLIENTE (CODIGO, NOME) AS (
  SELECT CUSTOMER_ID, CONCAT(FIRST_NAME, ' ', LAST_NAME)
  FROM CUSTOMER
)

SELECT * FROM DADOS_CLIENTE;

CREATE TABLE CLIENTE_PREMIUM 
(
  PAIS VARCHAR(50),
  CIDADE VARCHAR(100),
  CODIGO INT, 
  NOME VARCHAR(200), 
  EMAIL VARCHAR(200),
  PREMIUM INT
);


DROP PROCEDURE SELECIONA_CLIENTE_PREMIUM_D1;
DELIMITER $
CREATE PROCEDURE SELECIONA_CLIENTE_PREMIUM_D1(IN PARAM_META DECIMAL(10,2))
BEGIN
  DECLARE TOTAL_LINHAS INT DEFAULT 0;
  DECLARE CONTADOR INT DEFAULT 0;
  DECLARE VPAIS VARCHAR(50);
  DECLARE VCIDADE VARCHAR(100);
  DECLARE VCODIGO INT;
  DECLARE VNOME VARCHAR(200);
  DECLARE VEMAIL VARCHAR(200);
  DECLARE VPREMIUM INT;
  DECLARE VVALOR DECIMAL(10,2);
  
  SELECT COUNT(*) INTO TOTAL_LINHAS;
  
  WHILE CONTADOR <= TOTAL_LINHAS DO
     
     SELECT PAIS, CIDADE, CODIGO, NOME, EMAIL, VALOR
       INTO VPAIS, VCIDADE, VCODIGO, VNOME, VEMAIL, VVALOR
	 FROM 
       CLIENTE_LOCADORA
	 LIMIT 1 OFFSET CONTADOR; 
       
	 IF VVALOR >= PARAM_META THEN 
        INSERT INTO CLIENTE_PREMIUM (PAIS, CIDADE, CODIGO, NOME, EMAIL, PREMIUM)
           VALUES (VPAIS, VCIDADE, VCODIGO, VNOME, VEMAIL, 1);
	 END IF;
     
     SET CONTADOR = CONTADOR + 1;
     
  END WHILE;

END$
DELIMITER ;

CALL SELECIONA_CLIENTE_PREMIUM_D1(100);

SELECT * FROM CLIENTE_PREMIUM;