USE CLASSICMODELS;

DELIMITER $
CREATE PROCEDURE PLISTA_PRODUTO (INOUT LIST_PRODUTO TEXT)
BEGIN
 DECLARE DONE BOOL DEFAULT FALSE;
 DECLARE VAR_PRODUTO VARCHAR(50);
 
 DECLARE CURSOR_LISTA_PRODUTO CURSOR
 FOR 
	SELECT PRODUCTNAME FROM PRODUCTS;
    
 DECLARE CONTINUE HANDLER 
	FOR NOT FOUND SET DONE = true;	
    
 SET LIST_PRODUTO = '';
 
 OPEN CURSOR_LISTA_PRODUTO;
 
 PROCESS_LISTAPRODUTO: LOOP 
 
	FETCH CURSOR_LISTA_PRODUTO INTO VAR_PRODUTO;
    
    IF DONE = TRUE THEN
		LEAVE PROCESS_LISTAPRODUTO;
    END IF;
    
    SET LIST_PRODUTO = CONCAT(VAR_PRODUTO, " | ", LIST_PRODUTO);
    
 END LOOP;
 
 CLOSE CURSOR_LISTA_PRODUTO;
 
END$
DELIMITER ;

CALL PLISTA_PRODUTO(@LISTAPRODUTO);
select @LISTAPRODUTO;