USE CLASSICMODELS;

-- LETRA A
CREATE OR REPLACE VIEW PRODUTOS_VENDIDOS AS 
	SELECT PRODUCTNAME PRODUTO,  QUANTITYORDERED QUANTIDADE,
    PRICEEACH PRECO, QUANTITYORDERED * PRICEEACH TOTAL, PRODUCTCODE CODIGO
        FROM
        ORDERDETAILS JOIN PRODUCTS USING(PRODUCTCODE)
		ORDER BY (QUANTITYORDERED * PRICEEACH) DESC
        LIMIT 20;
        
	SELECT * FROM PRODUTOS_VENDIDOS;
    UPDATE PRODUTOS_VENDIDOS SET QUANTIDADE = 77 WHERE PRODUCTCODE = "S10_4698";
    DELETE FROM PRODUTOS_VENDIDOS WHERE PRODUCTCODE = "10_4698";
    -- Não é possivel alterar, pois essa chave primaria está presente em outras tabelas 
    
    DELETE FROM PRODUCTS WHERE PRODUCTCODE = "S10_4698";
    DELETE FROM ORDERDETAILS WHERE PRODUCTCODE = "S10_4698";
    -- Dessa forma, deletando em cada uma das tabelas onde essa chave existe, foi possivel deletar por completo
    
    
 -- LETRA B
 CREATE OR REPLACE VIEW VALORES_PRODUTOS_VENDIDOS AS
	SELECT AVG(PRICEEACH*QUANTITYORDERED) AS MEDIA, MAX(PRICEEACH*QUANTITYORDERED) AS MAIOR,
    MIN(PRICEEACH*QUANTITYORDERED) AS MENOR, PAYMENTDATE DATAP, OFFICES.CITY CIDADE, PRODUCTCODE PRODUTO
	FROM ORDERDETAILS JOIN ORDERS USING (ORDERNUMBER)
	JOIN CUSTOMERS USING (CUSTOMERNUMBER)
	JOIN EMPLOYEES ON (EMPLOYEES.EMPLOYEENUMBER = CUSTOMERS.SALESREPEMPLOYEENUMBER)
	JOIN OFFICES USING(OFFICECODE)
	JOIN PAYMENTS USING(CUSTOMERNUMBER)
	WHERE YEAR(PAYMENTDATE) = 2004 AND OFFICES.CITY ="PARIS"
	GROUP BY MONTH(PAYMENTDATE);

SELECT * FROM VALORES_PRODUTOS_VENDIDOS;
UPDATE VALORES_PRODUTOS_VENDIDOS SET DATAP = 2004-03-18  WHERE PRODUTO = "S10_1949";
DELETE FROM VALORES_PRODUTOS_VENDIDOS WHERE  PRODUTO = "S10_1949";
-- Não é possivel alterar, pois essa chave primaria está presente em outras tabelas 
    
    DELETE FROM PRODUCTS WHERE PRODUCTCODE = "S10_1949";
    DELETE FROM ORDERDETAILS WHERE PRODUCTCODE = "S10_1949";
    -- Dessa forma, deletando em cada uma das tabelas onde essa chave existe, foi possivel deletar por completo
    

-- LETRA C
CREATE OR REPLACE VIEW QUANTIDADE_PRODUTOS_REQUERIDOS AS
	SELECT ORDERDETAILS.QUANTITYORDERED QUANTIDADE, PRODUCTCODE PRODUTO
	FROM ORDERDETAILS JOIN ORDERS USING(ORDERNUMBER)
	WHERE MONTH(ORDERDATE) BETWEEN 9 AND 12
	GROUP BY PRODUCTCODE;

SELECT * FROM QUANTIDADE_PRODUTOS_REQUERIDOS;
UPDATE QUANTIDADE_PRODUTOS_REQUERIDOS SET QUANTIDADE = 40  WHERE PRODUTO = "S18_3782";
DELETE FROM QUANTIDADE_PRODUTOS_REQUERIDOS WHERE  PRODUTO = "S18_3782";
-- Não é possivel alterar, pois essa chave primaria está presente em outras tabelas 
    
    DELETE FROM PRODUCTS WHERE PRODUCTCODE = "S18_3782";
    DELETE FROM ORDERDETAILS WHERE PRODUCTCODE = "S18_3782";
    -- Dessa forma, deletando em cada uma das tabelas onde essa chave existe, foi possivel deletar por completo




-- LETRA D 
CREATE OR REPLACE VIEW TOTAL_CLIENTES AS
	SELECT COUNT(CUSTOMERNUMBER) CLIENTES, OFFICECODE ESCRITORIO
	FROM CUSTOMERS JOIN EMPLOYEES ON (EMPLOYEES.EMPLOYEENUMBER = CUSTOMERS.SALESREPEMPLOYEENUMBER)
	JOIN OFFICES USING(OFFICECODE)
	GROUP BY OFFICECODE
	ORDER BY COUNT(CUSTOMERNUMBER) DESC;

SELECT * FROM TOTAL_CLIENTES ;
UPDATE TOTAL_CLIENTES SET CLEINTES = 28  WHERE ESCRITORIO = "4";
DELETE FROM TOTAL_CLIENTES WHERE  ESCRITORIO = "4";
-- Não é possivel alterar, pois essa chave primaria está presente em outras tabelas 
    
    DELETE FROM EMPLOYEES WHERE OFFICECODE = "4";
    DELETE FROM OFFICES WHERE OFFICECODE = "4";
    -- Dessa forma, deletando em cada uma das tabelas onde essa chave existe, foi possivel deletar por completo

-- LETRA E 
CREATE OR REPLACE VIEW MENOS_VENDIDOS AS
	SELECT productCode PRODUTO, quantityOrdered QUANTIDADE
	FROM ORDERDETAILS JOIN ORDERS USING (orderNumber)
	JOIN PAYMENTS USING (CUSTOMERNUMBER)
	WHERE YEAR(PAYMENTDATE) = 2004 AND MONTH(PAYMENTDATE) BETWEEN 1 AND 6 
	ORDER BY QUANTITYORDERED ASC 
	LIMIT 15;

SELECT * FROM MENOS_VENDIDOS;
UPDATE MENOS_VENDIDOS SET QUANTIDADE = 2  WHERE PRODUTO = "S18_4409";
DELETE FROM MENOS_VENDIDOS WHERE  PRODUTO = "S18_4409";
-- Não é possivel alterar, pois essa chave primaria está presente em outras tabelas 
    
    DELETE FROM PRODUCTS WHERE PRODUCTCODE = "S18_4409";
    DELETE FROM ORDERDETAILS WHERE PRODUCTCODE = "S18_4409";
    -- Dessa forma, deletando em cada uma das tabelas onde essa chave existe, foi possivel deletar por completo
    
    
-- LETRA F
 CREATE OR REPLACE VIEW PRODUTOS_VENDIDOS_TOKYO AS
	SELECT AVG(PRICEEACH*QUANTITYORDERED) AS MEDIA, MAX(PRICEEACH*QUANTITYORDERED) AS MAIOR,
    MIN(PRICEEACH*QUANTITYORDERED) AS MENOR, PAYMENTDATE DATAP, OFFICES.CITY CIDADE, PRODUCTCODE PRODUTO
	FROM ORDERDETAILS JOIN ORDERS USING (ORDERNUMBER)
	JOIN CUSTOMERS USING (CUSTOMERNUMBER)
	JOIN EMPLOYEES ON (EMPLOYEES.EMPLOYEENUMBER = CUSTOMERS.SALESREPEMPLOYEENUMBER)
	JOIN OFFICES USING(OFFICECODE)
	JOIN PAYMENTS USING(CUSTOMERNUMBER)
	WHERE YEAR(PAYMENTDATE) = 2003 AND OFFICES.CITY ="TOKYO"
	GROUP BY MONTH(PAYMENTDATE);
    
SELECT * FROM PRODUTOS_VENDIDOS_TOKYO;
UPDATE PRODUTOS_VENDIDOS_TOKYO SET DATAP = 2003-04-22  WHERE PRODUTO = "S12_1108";
DELETE FROM PRODUTOS_VENDIDOS_TOKYO WHERE  PRODUTO = "S12_1108";
-- Não é possivel alterar, pois essa chave primaria está presente em outras tabelas 
    
    DELETE FROM PRODUCTS WHERE PRODUCTCODE = "S12_1108";
    DELETE FROM ORDERDETAILS WHERE PRODUCTCODE = "S12_1108";
    -- Dessa forma, deletando em cada uma das tabelas onde essa chave existe, foi possivel deletar por completo
    
-- LETRA G 
CREATE OR REPLACE VIEW MENOR_PRODUTOS_REQUERIDOS AS
	SELECT ORDERDETAILS.QUANTITYORDERED QUANTIDADE, PRODUCTCODE PRODUTO
	FROM ORDERDETAILS JOIN ORDERS USING(ORDERNUMBER)
	WHERE MONTH(ORDERDATE) BETWEEN 9 AND 12
	GROUP BY PRODUCTCODE
    ORDER BY QUANTIDADE ASC LIMIT 1;

SELECT * FROM MENOR_PRODUTOS_REQUERIDOS;
UPDATE MENOR_PRODUTOS_REQUERIDOS SET QUANTIDADE = 40  WHERE PRODUTO = "S24_4258";
DELETE FROM MENOR_PRODUTOS_REQUERIDOS WHERE  PRODUTO = "S24_4258";
-- Não é possivel alterar, pois essa chave primaria está presente em outras tabelas 
    
    DELETE FROM PRODUCTS WHERE PRODUCTCODE = "S24_4258";
    DELETE FROM ORDERDETAILS WHERE PRODUCTCODE = "S24_4258";
    -- Dessa forma, deletando em cada uma das tabelas onde essa chave existe, foi possivel deletar por completo
    
-- LETRA H
CREATE OR REPLACE VIEW CLIENTES_ESCRITORIO AS
	SELECT COUNT(CUSTOMERNUMBER) CLIENTES, OFFICECODE ESCRITORIO
    FROM OFFICES JOIN EMPLOYEES USING(OFFICECODE)
    JOIN CUSTOMERS ON(CUSTOMERNUMBER = EMPLOYEENUMBER)
    GROUP BY ESCRITORIO
    ORDER BY CLIENTES ASC;
    
SELECT * FROM CLIENTES_ESCRITORIO;
UPDATE CLIENTES_ESCRITORIO SET CLIENTES = 40  WHERE ESCRITORIO = "4";
DELETE FROM CLIENTES_ESCRITORIO WHERE  ESCRITORIO = "4";
-- Não é possivel alterar, pois essa chave primaria está presente em outras tabelas 
    
    DELETE FROM OFFICES WHERE OFFICECODE = "4";
    DELETE FROM EMLPLOYEES WHERE OFFICECODE = "4";
    -- Dessa forma, deletando em cada uma das tabelas onde essa chave existe, foi possivel deletar por completo
    

