USE CLASSICMODELS;
CREATE TABLE RESULTADO_ESCRITORIO(
ESCRITORIO VARCHAR(45),
PRODUTO VARCHAR(80), 
VALOR_VENDIDO DECIMAL(9,2),
META BOOL
)ENGINE=InnoDB;

CREATE OR REPLACE VIEW PRODUTO_ESCRITORIO AS 
	SELECT OFFICES.OFFICECODE, OFFICES.CITY, PRODUCTNAME,
    SUM(ORDERDETAILS.QUANTITYORDERED * ORDERDETAILS.PRICEEACH) AS TOTAL_VENDAS,
    COUNT(*) AS QUANT
    FROM OFFICES 
		JOIN EMPLOYEES USING(OFFICECODE)
        JOIN CUSTOMERS ON(OFFICES.OFFICECODE = EMPLOYEES.OFFICECODE)
        JOIN ORDERS USING(CUSTOMERNUMBER)
        JOIN ORDERDETAILS USING(ORDERNUMBER)
        JOIN PRODUCTS USING(PRODUCTCODE)
        GROUP BY OFFICES.OFFICECODE, PRODUCTNAME;
	
    SELECT * FROM PRODUTO_ESCRITORIO;






DELIMITER $
CREATE PROCEDURE REALIZOU_VENDA(IN PARAM_ESCRITORIO VARCHAR(45), IN PARAM_PRODUTO VARCHAR(80))
BEGIN
	DECLARE QUANT_VENDA INT DEFAULT 0;
    DECLARE PRO_META BOOL;
    DECLARE CONTA INT DEFAULT 0;
    DECLARE TOTAL_VENDIDO DECIMAL(10,2);
    
    SELECT COUNT(*) INTO QUANT_VENDA 
		FROM PRODUTO_ESCRITORIO
        WHERE CITY = PARAM_ESCRITORIO AND PRODUCTNAME = PARAM_PRODUTO
        LIMIT 1
        OFFSET CONTA;
        
	WHILE CONTA < QUANT_VENDA DO
		SELECT TOTAL_VENDAS INTO TOTAL_VENDIDO
			FROM PRODUTO_ESCRITORIO
            WHERE CITY = PARAM_ESCRITORIO AND PRODUCTNAME = PARAM_PRODUTO
            LIMIT 1
            OFFSET CONTA;
	IF TOTAL_VENDIDO >= 200000 THEN 
			SET PRO_META = TRUE;
		ELSE
			SET PRO_META = FALSE;
		END IF;
        
	INSERT INTO RESULTADO_ESCRITORIO (ESCRITORIO, PRODUTO, VALOR_VENDIDO, META)
		VALUES (PARAM_ESCRITORIO, PARAM_PRODUTO, TOTAL_VENDIDO, PRO_META);
        
	SET CONTA = CONTA + 1;
    END WHILE;
  
END$
DELIMITER ;

CALL REALIZOU_VENDA('San Francisco', 'Pont Yacht');
SELECT * FROM RESULTADO_ESCRITORIO;