DELIMITER $
CREATE PROCEDURE REALIZOU_VENDA(IN PARAM_ESCRITORIO VARCHAR(45), IN PARAM_PRODUTO VARCHAR(45))
BEGIN
   SELECT IFNULL(,0) INTO COUNT(PRODUCTNAME) NUMERO_PRODUTOS, CITY
    FROM OFFICES JOIN EMPLOYEES USING(OFFICECODE)
    JOIN CUSTOMERS ON(SALESREPEMPLYEENUMBER = EMPLOYEENUMBER)
    JOIN ORDERS USING(CUSTOMERNUMBER)
    JOIN ORDERDETAILS USING(ORDERNUMBER)
    JOIN PRODUCTS USING(PRODUCTCODE)
    WHERE PRODUCTNAME = PARAM_PRODUTO AND CITY = PARAM_ESCRITORIO AND NUMERO_PRODUTOS <= 200000;
  
END$
DELIMITER ;

CREATE TABLE RESULTADO_ESCRITORIO
( PRODUTO VARCHAR(60),
	VALOR_VENDIDO DECIMAL(9,2),
    META BOOL,
  ESCRITORIO VARCHAR(20)
) ENGINE = InnoDB;