CREATE DATABASE SINUCA;
USE SINUCA;

CREATE TABLE SACOLA 
(	NUMERO INT NOT NULL primary KEY,
	QUANTIDADE INT,
    COR VARCHAR(20)
)ENGINE = InnoDB;

DELIMITER $
CREATE PROCEDURE INSERIR_BOLA(IN PARAM_NUMERO INT, IN PARAM_QUANTIDADE INT, IN PARAM_COR VARCHAR(20))
BEGIN
	DECLARE CAPACIDADE INT DEFAULT 100;
	DECLARE QUANTIDADE_TOTAL INT DEFAULT 0;
	DECLARE QUANTIDADE_ATUAL INT DEFAULT 0;
	DECLARE TOTAL_INSERIR INT DEFAULT 0;

SELECT IFNULL(SUM(QUANTIDADE),0) INTO QUANTIDADE_TOTAL
FROM SACOLA;

SET TOTAL_INSERIR = QUANTIDADE_TOTAL + PARAM_QUANTIDADE;

IF TOTAL_INSERIR <= CAPACIDADE THEN
BEGIN
	SELECT IFNULL(SUM(QUANTIDADE),0) INTO QUANTIDADE_ATUAL 
    FROM SACOLA 
    WHERE NUMERO = PARAM_NUMERO;
    
    IF QUANTIDADE_ATUAL = 0 THEN 
    BEGIN
		IF PARAM_QUANTIDADE > 0 THEN
	BEGIN
		INSERT INTO SACOLA (NUMERO, QUANTIDADE, COR) VALUES (PARAM_NUMERO, PARAM_QUANTIDADE, PARAM_COR);
        SELECT CONCAT('Sucesso na inserção da bola: ',PARAM_NUMERO);
	END;
	ELSE
		SELECT CONCAT('O VALOR INSERIDO: ',PARAM_QUANTIDADE, 'DEVE SER MAIOR QUE 0');
	END IF;
    END;
    else
		CALL ALTERA_QUANTIDADE_BOLAS(PARAM_NUMERO, PARAM_QUANTIDADE, PARAM_COR);
END IF;

END;
ELSE 
	SELECT CONCAT('O VALOR INSERIDO: ',PARAM_QUANTIDADE, 'EXCEDEU A CAPACIDADE DA SACOLA');
    END IF;
    
END$
DELIMITER ;

DROP PROCEDURE INSERIR_BOLA;

CALL INSERIR_BOLA(8 ,10 , 'PRETA');

SELECT * FROM SACOLA;