CREATE DATABASE SINUCA;

USE SINUCA;

CREATE TABLE SACOLA
( NUMERO INT NOT NULL PRIMARY KEY, 
  QUANTIDADE INT,
  COR VARCHAR(20)
) ENGINE = InnoDB;

DELIMITER $
CREATE PROCEDURE INSERIR_BOLA(IN PARAM_NUMERO INT, IN PARAM_QUANTIDADE INT, IN PARAM_COR VARCHAR(20))
BEGIN
  DECLARE CAPACIDADE INT DEFAULT 100;  -- VARIÁVEL PARA VERIFICAR A CAPACIDADE
  DECLARE QUANTIDADE_TOTAL INT DEFAULT 0;  -- VARIÁVEL PARA VERIFICAR A QUANTIDADE TOTAL
  DECLARE QUANTIDADE_ATUAL INT DEFAULT 0;  -- VARIÁVEL PARA VERIFICAR 
  DECLARE TOTAL_INSERIR INT DEFAULT 0;

  SELECT IFNULL(SUM(QUANTIDADE),0) INTO QUANTIDADE_TOTAL
  FROM SACOLA;
  
  SET TOTAL_INSERIR = QUANTIDADE_TOTAL + PARAM_QUANTIDADE;
  
  IF TOTAL_INSERIR <= CAPACIDADE THEN
  BEGIN
  
    SELECT IFNULL(SUM(QUANTIDADE),0) INTO QUANTIDADE_ATUAL
    FROM SACOLA
    WHERE NUMERO = PARAM_NUMERO;
  
    IF QUANTIDADE_ATUAL = 0 THEN
    BEGIN
      IF PARAM_QUANTIDADE > 0 THEN
      BEGIN
         INSERT INTO SACOLA (NUMERO, QUANTIDADE, COR) VALUES (PARAM_NUMERO, PARAM_QUANTIDADE, PARAM_COR);
	     SELECT CONCAT('SUCESSO NA INSERÇÃO DA BOLA DE NÚMERO: ', PARAM_NUMERO) AS MENSAGEM;
      END;
      ELSE
         SELECT CONCAT('O VALOR INSERIDO: ', PARAM_QUANTIDADE, ' DEVE SER MAIOR QUA ZERO') AS MENSAGEM;
	  END IF;
    END;
    ELSE 
      CALL ALTERA_QUANTIDADE_BOLAS(PARAM_NUMERO, PARAM_QUANTIDADE, PARAM_COR);
	END IF;
  END;
  ELSE 
    SELECT CONCAT('O VALOR INSERIDO: ', PARAM_QUANTIDADE, ' EXCEDEU A CAPACIDADE DA SACOLA') AS MENSAGEM;
  END IF;
  
END$
DELIMITER ;


DELIMITER $
CREATE PROCEDURE ALTERA_QUANTIDADE_BOLAS(IN PARAM_NUMERO INT, IN PARAM_QUANTIDADE INT, IN PARAM_COR VARCHAR(20))
BEGIN
  DECLARE CAPACIDADE INT DEFAULT 100;
  DECLARE QUANTIDADE_TOTAL INT DEFAULT 0;
  DECLARE QUANTIDADE_ATUAL INT DEFAULT 0;
  DECLARE TOTAL_ALTERAR INT DEFAULT 0;
  
  
  SELECT IFNULL(SUM(QUANTIDADE),0) INTO QUANTIDADE_TOTAL
  FROM SACOLA;
  
  SET TOTAL_ALTERAR = QUANTIDADE_TOTAL + PARAM_QUANTIDADE;
  
  IF TOTAL_ALTERAR <= CAPACIDADE THEN
  BEGIN
    SELECT IFNULL(SUM(QUANTIDADE),0) INTO QUANTIDADE_ATUAL
    FROM SACOLA
    WHERE NUMERO = PARAM_NUMERO; 
    
    IF QUANTIDADE_ATUAL > 0 THEN
    BEGIN
      SET TOTAL_ALTERAR = QUANTIDADE_ATUAL + PARAM_QUANTIDADE;
      
      IF TOTAL_ALTERAR > 0 THEN
	  BEGIN
        UPDATE SACOLA SET QUANTIDADE = TOTAL_ALTERAR WHERE NUMERO = PARAM_NUMERO;
        SELECT CONCAT('SUCESSO NA ALTERAÇÃO DA QUANTIDADE DE BOLAS DE NÚMERO: ', PARAM_NUMERO) AS MENSAGEM;
      END;
      ELSE 
        CALL EXCLUIR_BOLA(PARAM_NUMERO);
	  END IF;
      
    END;
    ELSE
      CALL INSERIR_BOLA(PARAM_NUMERO, PARAM_QUANTIDADE, PARAM_COR);
	END IF;
  END;
  ELSE 
    SELECT CONCAT('O VALOR INSERIDO: ', PARAM_QUANTIDADE, ' EXCEDEU A CAPACIDADE DA SACOLA') AS MENSAGEM;
  END IF;
END$
DELIMITER ;


CALL ALTERA_QUANTIDADE_BOLAS(2, -10, 'AZUL');

SELECT * FROM SACOLA;



-- Procedure de DELETE
DELIMITER $
CREATE PROCEDURE EXCLUIR_BOLA(IN PARAM_NUMERO INT)
BEGIN 
  DECLARE NUMERO_EXISTENTE INT DEFAULT 0;
  
	
	SELECT IFNULL(NUMERO,0) INTO NUMERO_EXISTENTE
    FROM SACOLA
    WHERE NUMERO = PARAM_NUMERO; 
    IF NUMERO_EXISTENTE = 0 THEN
    SELECT CONCAT('BOLA DE NUMERO ', PARAM_NUMERO, ' NÃO EXISTE NA SACOLA') AS MENSAGEM;
	ELSE
    BEGIN
    DELETE FROM SACOLA WHERE NUMERO = PARAM_NUMERO;
    SELECT CONCAT('BOLA DE NUMERO ', PARAM_NUMERO, ' EXCLUIDA COM SUCESSO ') AS MENSAGEM;
    END;
    END IF;
END$
DELIMITER ;

