/*  TRABALHO DE BANCO DE DADOS 2 - ATIVIDADE AVALIATIVA 3 */

-- ROTEIRO DO TRABALHO
-- SUGESTÃO: CRIAR DUAS PROCEDURES
   -- 1º: GERAR_PEDIDO
   -- 2ª: GERAR_ITEM_PEDIDO
   
-- DEVE EXISTIR UMA LISTA DE PRODUTO RELACIONADOS COM O CLIENTE.
-- CRIAR UMA TABELA DE CARRINHO DE COMPRA
   -- CODIGOPRODUTO, QUANTIDADE, PREÇO, CODIGOCLIENTE
   -- S10_1678     , 100       , 50.00, 112
   
-- QUEM SÃO OS CLIENTES QUE PODEM SER UTILIZADOS NOS TESTES
   SELECT * FROM CLASSICMODELS.CUSTOMERS WHERE SALESREPEMPLOYEENUMBER IS NOT NULL;
   
-- QUEM SÃO OS VENDEDOS QUE PODEM SER UTILIZADOS NOS TESTES
   SELECT * FROM CLASSICMODELS.EMPLOYEES WHERE JOBTITLE = 'SALES REP';

-- LEMBRANDO QUE OS PRODUTOS DEVEM EXISTIR NA BASE DE DADOS.
   SELECT * FROM CLASSICMODELS.PRODUCTS;
   
   
DELIMITER $
CREATE PROCEDURE GERAR_PEDIDO(IN PARAM_CODIGOCLIENTE INT, IN PARAM_CODIGOVENDEDOR INT, OUT RESULTADO VARCHAR(200))
BEGIN
  -- 1º DECLARAR AS VARIÁVEIS NECESSÁRIAS;
  -- 2º VERIFICAR SE O CLIENTE INFORMADO EXISTE NA BASE
  -- 3º VERIFICAR SE O VENDEDOR INFORMADO EXISTE NA BASE
  -- 4º VERIFICAR SE O CLIENTE REALIZOU COMPRA NO CARRINHO
  -- 5º ABRIR UMA TRANSAÇÃO
  -- 6º CRIAR UM PEDIDO PARA O CLIENTE (INSERIR UM PEDIDO EM ORDERS)
  -- 7º IDENTIFICAR A QUANTIDADE DE PRODUTOS QUE EXISTEM NO CARRINHO
  -- 8º INICIAR O LOOP
  -- 9º CHAMAR A MINHA PROCEDURE DE GERAÇÃO DE ITENS DO PEDIDO
     CALL GERAR_ITEM_PEDIDO(CODIGOPRODUTO, QUANTIDADE, PRECO, NUMEROPEDIDO);
       -- 9.1 DECLARAÇÃO DE VARIÁVEIS
       -- 9.2 VERIFICAR SE O PRODUTO EXISTE
       -- 9.3 VERIFICAR SE ATENDE A QUANTIDADE SOLICITADA
       -- 9.4 INSERIR OS DADOS DO ITEM DO PEDIDO ( INCLUIR UM REGISTO EM ORDERDETAIS)
       -- 9.5 ATUALIZAR O ESTOQUE (UPDATE NA TABELA PRODUCTS)
       -- SUGESTÃO: CRIAR UMA TABELA DE RESULTADO DO ITEM DE PEDIDO
    -- 10º ATUALIZAR O CLIENTE COM O VENDEDOR (UPDATE EM CUSTOMERS NO CAMPO SALESREPEMPLOYEENUMBER)
    -- 11º RESULTADO RECEBE SUCESSO OU PEDIDO GERADO: NUMERO DO PEDIDO
    -- 12º COMMIT
    -- 13º FECHAR TRANSAÇÃO
END$
DELIMITER ;
DELIMITER ;