use classicmodels;
CREATE TABLE AUDITORIA (
	DATAMODIFICACAO DATETIME, 
    HISTORICO TEXT
);

DELIMITER $
CREATE TRIGGER TRG_INSERIR_CLIENTE AFTER INSERT ON CUSTOMERS
FOR EACH ROW 
BEGIN 
	INSERT INTO AUDITORIA VALUES(NOW(), CONCAT('FOI INCLUIDO NA TABELA O CLIENTE DE NUMERO: ', NEW.CUSTOMERNUMBER));
END$

CREATE TRIGGER TRG_ALTERAR_CLIENTE AFTER UPDATE ON CUSTOMERS
FOR EACH ROW 
BEGIN 
	INSERT INTO AUDITORIA VALUES(NOW(), CONCAT('FOI TROCADO NA TABELA O CLIENTE DE NUMERO: ', OLD.CUSTOMERNUMBER, ' PARA NOVO: ', NEW.CUSTOMERNUMBER));
END$

CREATE TRIGGER TRG_EXCLUIR_CLIENTE AFTER DELETE ON CUSTOMERS
FOR EACH ROW 
BEGIN 
	INSERT INTO AUDITORIA VALUES(NOW(), CONCAT('FOI EXCLUIDO O CLIENTE DE NUMERO: ', OLD.CUSTOMERNUMBER));
END$
DELIMITER ;

INSERT INTO CUSTOMERS VALUES(95515, 'Luiz teste', 'Fulano', 'Fulano 2', '3333-3333', 'Rua Teste 1', 'Rua teste 2', 'Belo Horizonte', 'MG', '', 'Brasil', null, 0.00);
SELECT * FROM CUSTOMERS;  	
UPDATE CUSTOMERS SET CUSTOMERNUMBER = 502 WHERE CUSTOMERNUMBER = 501; 
DELETE FROM CUSTOMERS WHERE CUSTOMERNUMBER = 502;
select*from auditoria;
