SELECT 
  CUSTOMERNAME, 
  CITY, 
  COUNTRY,
  PHONE
FROM 
  CUSTOMERS;
  
  
/*
Introdução ao With
É gerada uma tabela virtual, mas ela vista apenas dentro do contexto. 
Entende-se por contexto, o ponto e virgula.
*/

WITH DADOSCLIENTE_WITH (NOME, CIDADE, PAIS, TELEFONE, CODIGO)
AS 
(
 SELECT 
  CUSTOMERNAME, 
  CITY, 
  COUNTRY,
  PHONE, 
  CUSTOMERNUMBER
FROM 
  CUSTOMERS
)

SELECT NOME, CIDADE, PAIS, TELEFONE, SUM(AMOUNT) TOTAL
FROM DADOSCLIENTE_WITH 
  JOIN PAYMENTS ON (CODIGO = CUSTOMERNUMBER)
GROUP BY 
  NOME, CIDADE, PAIS, TELEFONE;
  
SELECT * FROM DADOSCLIENTE;


/*
Introdução ao View
É gerada uma tabela virtual e esta é gravada no banco de dados.
Pode ser reutilizada
*/

CREATE OR REPLACE VIEW DADOSCLIENTE
AS
   SELECT 
  CUSTOMERNAME, 
  CITY, 
  COUNTRY,
  PHONE, 
  CUSTOMERNUMBER
FROM 
  CUSTOMERS;
  
  
SELECT * FROM DADOSCLIENTE;

/*
Realizando ações na VIEWS
*/


UPDATE DADOSCLIENTE SET PAIS = 'BRAZIL' WHERE CODIGO = 103;

SELECT * FROM CUSTOMERS WHERE CUSTOMERNUMBER = 103;

-- 1º PASSO  
DELETE FROM ORDERDETAILS WHERE ORDERNUMBER IN (SELECT ORDERNUMBER FROM ORDERS WHERE CUSTOMERNUMBER = 103);
-- 2º PASSO
DELETE FROM ORDERS WHERE CUSTOMERNUMBER = 103;
-- 3º PASSO
DELETE FROM PAYMENTS WHERE CUSTOMERNUMBER = 103;
-- ULTIMO PASSO
DELETE FROM DADOSCLIENTE WHERE CODIGO = 103;
