use classicmodels;
-- QUESTAO 1
-- LETRA A
SELECT 
	CUSTOMERNAME AS CLIENTE , CITY AS CIDADE , SUM(AMOUNT) AS PAGO
FROM 
	CUSTOMERS 
    LEFT JOIN PAYMENTS
    USING(CUSTOMERNUMBER)
    WHERE  YEAR (PAYMENTDATE) = 2004 OR CREDITLIMIT = 0 
    GROUP BY CUSTOMERNAME
    HAVING SUM(AMOUNT) < 50000;
    
    
-- LETRA B
SELECT 
 FIRSTNAME AS VENDEDOR, OFFICES.CITY AS ESCRITORIO, COUNT(salesRepEmployeeNumber) AS VENDAS, AMOUNT*0.03 AS BONUS
 FROM EMPLOYEES
 JOIN CUSTOMERS ON(salesRepEmployeeNumber = EMPLOYEENUMBER)
 JOIN PAYMENTS USING (CUSTOMERNUMBER)
 JOIN OFFICES USING(OFFICECODE)
 WHERE YEAR (PAYMENTDATE) = 2005 AND MONTH (PAYMENTDATE) in (1,2,3) AND OFFICES.CITY IN ('SAN FRANCISCO', 'PARIS') 
 GROUP BY FIRSTNAME 
 ORDER BY MONTH(PAYMENTDATE) ASC;
 
 -- LETRA C 
create table Avatar(
id_Avatar int not null  primary key,
id_Jogo int,
nome varchar(80),
habilidade varchar(80),
ponto_fraco	varchar(50)
)ENGINE=InnoDB;

create table Acessorio(
id_Acessorio int not null  primary key,
id_Avatar int,
id_Nivel int,
descricao varchar(80),
foreign key (id_Avatar) references Avatar(id_Avatar) on delete cascade
)ENGINE=InnoDB;

-- LETRA D
SELECT PRODUCTNAME AS PRODUTO, PRICEEACH AS PRECO, QUANTITYORDERED AS VENDIDO
FROM PRODUCTS 
JOIN ORDERDETAILS USING(PRODUCTCODE)
JOIN ORDERS USING(ordernumber)
JOIN CUSTOMERS USING (CUSTOMERNUMBER)
JOIN EMPLOYEES ON(salesRepEmployeeNumber = EMPLOYEENUMBER)
JOIN OFFICES USING(OFFICECODE)
WHERE YEAR (ORDERDATE) = 2004 AND MONTH (ORDERDATE) IN(7,8,9) AND OFFICES.CITY = 'PARIS'
UNION
SELECT PRODUCTNAME AS PRODUTO, PRICEEACH AS PRECO, QUANTITYORDERED AS VENDIDO
FROM PRODUCTS 
JOIN ORDERDETAILS USING(PRODUCTCODE)
JOIN ORDERS USING(ordernumber)
JOIN CUSTOMERS USING (CUSTOMERNUMBER)
JOIN EMPLOYEES ON(salesRepEmployeeNumber = EMPLOYEENUMBER)
JOIN OFFICES USING(OFFICECODE)
WHERE YEAR (ORDERDATE) = 2005 AND MONTH (ORDERDATE) IN(1,2,3) AND OFFICES.CITY = 'LONDON';




-- QUESTAO 2
USE world;
SELECT SUM(PERCENTAGE*COUNTRY.POPULATION)/100 AS TotalFalantes, country.name as PAIS, REGION AS REGIAO
FROM COUNTRY 
JOIN COUNTRYLANGUAGE ON(COUNTRYCODE = CODE)
JOIN CITY USING(COUNTRYCODE)
WHERE CONTINENT = 'NORTH AMERICA';
